name: Auto Cherry-Pick to Stable Branches

on:
  push:
    branches:
      - main

jobs:
  cherry-pick:
    if: github.event.head_commit.author.name == 'anupriya13'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_branch: [0.80-stable, 0.79-stable]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for full commit history

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest merge commit from main
        id: get_commit
        run: |
          MERGE_COMMIT=$(git log -1 --merges --pretty=format:"%H")
          echo "MERGE_COMMIT=$MERGE_COMMIT" >> $GITHUB_ENV

      - name: Cherry-pick and push to new branch
        run: |
          git fetch origin ${{ matrix.target_branch }}
          git checkout -b cherry-pick-${{ env.MERGE_COMMIT }}-${{ matrix.target_branch }} origin/${{ matrix.target_branch }}

          if git cherry-pick -m 1 $MERGE_COMMIT; then
            git push origin HEAD
          else
            echo "❌ Cherry-pick failed. Possibly conflicts."
            exit 1
          fi

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "chore: Cherry-pick $MERGE_COMMIT into ${{ matrix.target_branch }}" \
            --body "Automated cherry-pick of commit $MERGE_COMMIT into ${{ matrix.target_branch }}" \
            --base "${{ matrix.target_branch }}" \
            --head "cherry-pick-${MERGE_COMMIT}-${{ matrix.target_branch }}" \
            --repo "${{ github.repository }}"
