name: Generate Release Notes

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.12

      - name: Install dependencies
        run: pip install requests

      - name: Generate release notes file
        run: |
          python .github/scripts/generate_release_notes.py > release_notes.md
          mkdir -p .github/release_notes
          mv release_notes.md .github/release_notes/release_notes.md

      - name: Commit and push release notes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/release_notes/release_notes.md
          git commit -m "Add generated release notes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
